server:
  port: ${BOOKING_SERVER_PORT:8001}
  servlet:
    context-path: /booking-service
spring:
  application:
    name: '@name@'
    version: '1.0.0'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BOOKING_DB_HOST:localhost}:${BOOKING_DB_PORT:3360}/${BOOKING_DB_NAME:booking_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: ${BOOKING_DB_USERNAME:root}
    password: ${BOOKING_DB_PASSWORD:admin}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true

app:
  rabbitmq:
    exchange:
      booking-room: exchange.booking-room
    routing-key:
      booking-room-requested: routing-key.booking-room-requested
      booking-room-confirmation: routing-key.booking-room-confirmation
    queue:
      booking-room-requested: booking-room-requested
      booking-room-confirmation: booking-room-confirmation
