server:
  port: ${CUSTOMER_SERVER_PORT:8002}
  address: 0.0.0.0
  servlet:
    context-path: /customer-service
spring:
  application:
    name: '@name@'
    version: '1.0.0'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:mysql://${CUSTOMER_DB_HOST:localhost}:${CUSTOMER_DB_PORT:3360}/${CUSTOMER_DB_NAME:customer_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: ${HOTEL_DB_USERNAME:root}
    password: ${HOTEL_DB_PASSWORD:admin}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
app:
  rabbitmq:
    exchange:
      customer-booking: exchange.customer-booking
    routing-key:
      customer-booking-update: routing-key.customer-booking-update
    queue:
      customer-booking-update: customer-booking-update

