server:
  port: ${PAYMENT_SERVER_PORT:8003}
  servlet:
    context-path: /payment-service
spring:
  application:
    name: '@name@'
    version: '1.0.0'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  payment:
    mock:
      failure-chance-percentage: ${FAILURE_CHANCE_PERCENTAGE:1}
  rabbitmq:
    exchange:
      payment: exchange.payment
    routing-key:
      payment-request: routing-key.payment-request
      payment-confirmation: routing-key.payment-confirmation
    queue:
      payment-request: payment-request
      payment-confirmation: payment-confirmation
